### ISSUE TITLE
Should GEOM_DIMENSION tag be of type DENSE?

### ISSUE THREAD

**Issue by akoen** [Thea-Energy/stellarmesh#1]
Cubit plugin uses SPARSE, cad-to-dagmc and cad-to-openmc use DENSE.

**Comment by gonuke** [comment]
I think SPARSE is the right choice here. Only the entity sets containing vertices get tagged with `geom_dimension` and they are definitely a minority of the entities in the model, esp. with dense faceting.  A DENSE tag will reserve memory to tag every entity and be more efficient about access to that memory.  A SPARSE tag will only reserve as much memory as needed with small (negligible?) lookup penalty.

**Comment by akoen** [comment]
Thanks! Closing
