### ISSUE TITLE
Allow stl import

### ISSUE THREAD

**Issue by shimwell** [Thea-Energy/stellarmesh#15]
Currently brep and step files are allowable import formats.

In theroy this package could also allow stl import via moab directly.

It might be a bit different to the existing import files but might be worth considering

**Comment by akoen** [comment]
What's your imagined use-case for this? Would you be mixing brep models and stl models? Of course it's totally possible to import stls with gmsh or moab but would require some rethinking of how surface sense is handled.

**Comment by shimwell** [comment]
I would guess a user has stl geometry for the whole model,  perhaps from a serpent2 simulation. I imagine a user case where they want to simulate the same serpent2 stl model in dag openmc. It looks like you can already do it, so perhaps just an example in the examples folder
