### ISSUE TITLE
import_step not working

### ISSUE THREAD

**Issue by stefan-richr** [Thea-Energy/stellarmesh#16]
Ran code to import step file (2 solids)
import build123d as bd
import stellarmesh as sm
geometry = sm.Geometry
geometry.import_step(filename='blanket_both.stp', material_names=['SiC', 'breed'])
mesh = sm.Mesh.mesh_geometry(geometry, min_mesh_size=10, max_mesh_size=50)

And received error telling me geometry has no solid attribute.

**Comment by sjcrs** [comment]
First, if you have a STEP file already, you don't need to import build123d. 

For the `import_step` call, try

    geometry = sm.Geometry.import_step(filename='blanket_both.stp', material_names=['SiC', 'breed'])

**Comment by akoen** [comment]
Closing as this issue was discussed and presumably resolved at https://openmc.discourse.group/t/error-meshing-cad-geometry/3472/8
